

=== Goals

[quote]
"any project should start off with some notion what of what you're trying to achieve. ... high-level project goals ... Touch the magic."
-- Bill Buzbee, Magic-1 project http://www.homebrewcpu.com/



=== Inspirational quotes

[quote]
"People who are really serious about software should make their own hardware"
-- Alan Kay, https://www.adafruit.com/quotes

[quote]
"physically constructing a CPU ... since it allows students to probe the inner workings of the CPU, it helps them "Touch the magic", helps them learn and understand the underlying electronics and hardware."
-- David Cary, https://en.wikibooks.org/wiki/Microprocessor_Design/Wire_Wrap

[quote]
____
...
Reply by Mike Butts * May 24, 2002
...

I was co-designer of the Nova 4 / Eclipse S140 16-bit processor back in '77.
It was 2901 based, plus lots of TTL. I don't remember whether we used
any PALs or not. The "Eagle" machine immortalized in "Soul of a New
Machine" was 32-bit and heavily PAL based.

Nova 4 was DG's first DRAM-only machine, no provision for core
memory. That mattered to the processor because all core memory
cycles had to be read-modify-write. Reading a core erases it. The only
difference between Nova 4 and Eclipse S140 was the microcode and
the price. An old game. Dave Grondalski and I designed the logic
and wrote the microcode. Two classic parts, the AMD 2901 bitslice
and the Mostek 16K RAS/CAS DRAM.

If you're reading this email and you never read "Soul of a New Machine",
go read it *right now*. I've never seen another book that had the
technology right, the people right, and was so well written. I was two
aisles over from those guys at the time of the book, and it's uncannily
spot on.
http://www.powells.com/cgi-bin/biblio?inkey=1-0316491977-0

--Mike Butts http://www.easystreet.com/~mbutts/xr16vx_jhdl.html
...
--
https://www.embeddedrelated.com/showthread/fpga-cpu/1193-1.php "PAL/GAL CPUs?"
____

=== Relay computer

=== addressing modes

The earliest CPUs had
only one way to refer to an address in memory:
the full absolute address as part of the instruction.
This forced instructions
(at least those that LOAD or STORE values to memory)
to be *longer* than an address.
(This also seems to mandate
allowing self-modifying code
in order to handle arrays, stacks, pointers, etc.
).

This restriction is awkward, because

[loweralpha]
. we want to maximize the bits in our address
. we want to load the entire instruction in a single cycle
. we want to minimize the data bus width, to reduce hardware costs.

Later mainframes had a huge variety of addressing modes.

Much later, RISC machines typically
had only one LOAD and one STORE instruction,
which was kind of complicated
but could emulate
most of those addressing modes in a single instruction
(and, of course, all of those addressing modes
if multiple instructions or a loop were allowed.
).
That addressing mode was:

    LOAD REG(dest):=MEM(offset + REG(base) + REG(index) )

DAV wants to make a CPU as simple as possible:
So the self-modifying code approach is tempting --
those designers surely knew something
about making computers as simple as possible.
But I'm leaning towards a simplified

    LOAD REG(dest):= MEM(REG(source))
    
even though the fully general form of the above RISC LOAD
now requires 3 instructions:

    ADD REG(t):= REG(base) + offset
    ADD REG(t):= REG(t) + REG(index)
    LOAD REG(dest):= MEM(REG(t))

.

But rather than 2 different ADD instructions,

    ADD Ra := Rb + Rc
    ADD Ra := Rb + constant

perhaps it might simplify the hardware to combine them,
resulting in the above RISC LOAD
requiring 2 instructions in the fully general case:

    ADD REG(t):= REG(base) + REG(index) + offset
    LOAD REG(dest):= MEM(REG(t))

(That ADD is know as LEA: "load effective address"
on some architectures).






